#!/bin/bash
#       基于FEH和在线API实现的在线实时更换壁纸
#	A Wallpaper Auto Change Script for Bspwm and Feh
#       作者 Author：PandaQuQ
#       url: https://git.pandaquq.tk/panda/WACSBF

function getWP(){
	if [ $1 -eq 1 ]
	then
		wget https://www.eatshit.cn/ -O ~/.config/WACSBF/cache/1
		grep -o  -a -E '/images-t/.*\.jpg'  ~/.config/WACSBF/cache/1  > ~/.config/WACSBF/cache/2
		url1=$(cat ~/.config/WACSBF/cache/2)
		url_real="https://www.eatshit.cn${url1}"
		wget $url_real -O ~/.config/bspwm/theme/wallpapers/$2.jpg
		rm -rf ~/.config/WACSBF/cache/*
	elif [ $1 -eq 2 ] 
	then
		wget https://api.ixiaowai.cn/api/api2.php --no-check-certificate -O ~/.config/bspwm/theme/wallpapers/$2.jpg
	elif [ $1 -eq 3 ]
	then
		wget `curl "https://img.xjh.me/random_img.php?type=bg"  | grep -o -E  'img\.xjh\.me/img/[[:digit:]]{2,10}_p[[:digit:]]\.jpg' | grep -o -E  'img\.xjh\.me/img/[[:digit:]]{2,10}_p[[:digit:]]\.jpg' -m 1 ` -O wget `curl "https://img.xjh.me/random_img.php?type=bg"  | grep -o -E  'img\.xjh\.me/img/[[:digit:]]{2,10}_p[[:digit:]]\.jpg' | grep -o -E  'img\.xjh\.me/img/[[:digit:]]{2,10}_p[[:digit:]]\.jpg' -m 1 ` -O ~/.config/bspwm/theme/wallpapers/$2.jpg
	elif [ $1 -eq 4 ]
	then
		wget `curl "https://tuapi.eees.cc/api .php?category=dongman&px=pc" |  grep -o -E  'https://tuapi\.eees\.cc/dongman/pc/TUAPI-EEES-CC-[[:digit:]]{2,12}\.jpg' ` -O ~/.config/bspwm/theme/wallpapers/$2.jpg
	elif [ $1 -eq 5 ]
	then
		wget https://t.mwm.moe/fj/ --no-check-certificate -O ~/.config/bspwm/theme/wallpapers/$2.jpg
	fi

}

function selWP(){

        for ((i=1;i<=3;i++))
        do
        	getWP $@ $i
        done
        
        return 0
}

function changeWP(){
	mark=~/.config/WACSBF/notfirstmark
	if [[ -f "$mark" ]]; then
		feh --randomize --no-fehbg --bg-fill ~/.config/bspwm/theme/wallpapers/
		rm ~/.config/bspwm/theme/wallpapers/*
		selWP $@
	else
		rm ~/.config/bspwm/theme/wallpapers/*
		selWP $@
		feh --randomize --no-fehbg --bg-fill ~/.config/bspwm/theme/wallpapers/
		touch ~/.config/WACSBF/notfirstmark
	fi
}



#1是4k风景图 2是小歪动漫api  3是xjh api  4是eees图片api
#APIS: Eatshit.cn ixiaowai.cn xjh.me eees.cc

#参数 1 为4k风景 2、3、4、5为动漫
#现在只有5生效了
#Parameter 1 Landscape 2,3,4,5 Anime
#Now only 5 is valid
changeWP 5



